### PR TITLE
Add gzip compression support for npm lookups [0.16]

### PR DESCRIPTION
**Pull request by AdamBurgess**
gotta get that pull request karma :smile: (it'd be very understandable if you'd prefer to do it manually too, but github only counts merged PRs on the master branch!) 
this is for master branch
see https://github.com/jspm/npm/pull/133 for comments

### CODE REVIEW

**Comment by jordie23** [comment]
Any way we can flag this as important? :/

**Comment by guybedford** [comment]
:+1: merged manually.

@AdamBurgess my apologies to your PR foo, I happend to merge the 0.17 first, and branch commits don't seem to get counted from what I can gather.

**Comment by guybedford** [comment]
Actually this did merge fine, GitHub was just sending mixed signals with this outage.

**Comment by kayue** [comment]
Thanks @AdamBurgess :+1:

**Pull request closed without merging**
