### PR TITLE
Refactor custom scope authentication

### PR DESCRIPTION
**Pull request by glen-84**
The `download` method wasn't working. I really don't know how this worked before.

I decided to do some refactoring as well, and introduced a `registryInfo` method similar to what you described.

Please let me know what you think.

### CODE REVIEW

**Comment by guybedford** [comment]
@glen-84 thanks for this. Can you explain why the download method wasn't working here?

**Comment by glen-84** [comment]
Well, it was always using `self.auth` (when appropriate), so it never would have sent the scope-specific auth. I was getting a 401 on the download for my scoped package.

Also, it would probably have been using the wrong registry URL (not scope-specific).

**Comment by guybedford** [comment]
Sure, thanks, I will try it out here.

**Comment by glen-84** [comment]
@guybedford How's it looking?

**Comment by glen-84** [comment]
@guybedford Will there be a release soon?

**Comment by guybedford** [comment]
@glen-84 sure I've posted this out now.

**Pull request merged**
